name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun i
        working-directory: lib
      - run: |
          bun i
          bun run build
          bun run compile
          bun run zip
        working-directory: consume
      - uses: svenstaro/upload-release-action@v2
        with:
          file: "consume/${{ github.event.repository.name }}.zip"
          overwrite: true
